#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="ios/DejaGroove/Config/Release.local.xcconfig"

required=(
  DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL
  DEJA_GROOVE_RECOGNITION_PROXY_KEY
)

for key in "${required[@]}"; do
  if [ -z "${!key:-}" ]; then
    echo "Missing required secret: ${key}" >&2
    exit 1
  fi
  if [[ "${!key}" == *$'\n'* || "${!key}" == *$'\r'* ]]; then
    echo "Secret ${key} must be a single-line value." >&2
    exit 1
  fi
done

if [[ "${DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL}" != https://* ]]; then
  echo "DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL must use HTTPS." >&2
  exit 1
fi

if [[ "${DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL}" == *func-deja-recognition.example* ]]; then
  echo "DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL still points at the placeholder host." >&2
  exit 1
fi

if [[ "${DEJA_GROOVE_RECOGNITION_PROXY_KEY}" == REPLACE_* ]]; then
  echo "DEJA_GROOVE_RECOGNITION_PROXY_KEY still contains a placeholder value." >&2
  exit 1
fi

echo "::add-mask::${DEJA_GROOVE_RECOGNITION_PROXY_KEY}"

mkdir -p "$(dirname "${CONFIG_PATH}")"

xcconfig_proxy_url="${DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL/https:\/\//https:\$(URL_SLASH)\$(URL_SLASH)}"

cat > "${CONFIG_PATH}" <<EOF
// Generated by the TestFlight workflow. Do not commit.
DEJA_GROOVE_RUNTIME_MODE = local_proxy
DEJA_GROOVE_RECOGNITION_PROXY_BASE_URL = ${xcconfig_proxy_url}
DEJA_GROOVE_RECOGNITION_PROXY_KEY = ${DEJA_GROOVE_RECOGNITION_PROXY_KEY}
EOF

echo "Wrote ${CONFIG_PATH} for Release archive configuration."
